/**
 * pages/Report.tsx
 * Permalink page for a cached report (/report/:id).
 * UI.md §8.2: topbar + results block only (no input card).
 * SECURITY.md §15: noindex meta tag required — report pages must not be indexed.
 * SECURITY.md §15: report IDs are non-sequential (generated by backend).
 */

import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { getReport, ApiError } from '../services/api';
import type { FullReport } from '../types/api';
import { ResultsBlock } from '../components/ResultsBlock';
import { Footer } from '../components/Footer';

export function Report() {
  const { id } = useParams<{ id: string }>();
  const [report, setReport] = useState<FullReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) {
      setError('Invalid report ID.');
      setLoading(false);
      return;
    }

    let cancelled = false;
    setLoading(true);
    setError(null);

    getReport(id)
      .then((r) => {
        if (!cancelled) {
          setReport(r);
          setLoading(false);
        }
      })
      .catch((err) => {
        if (!cancelled) {
          if (err instanceof ApiError && err.status === 404) {
            setError('Report not found. It may have expired or the link may be incorrect.');
          } else {
            setError('Could not load this report. Please try again.');
          }
          setLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [id]);

  useEffect(() => {
    // SECURITY.md §15: noindex so search engines don't index report pages.
    // Dynamic meta tag injection since rendering <head> inside body is ignored by browsers.
    let meta = document.querySelector('meta[name="robots"]');
    let created = false;
    if (!meta) {
      meta = document.createElement('meta');
      meta.setAttribute('name', 'robots');
      document.head.appendChild(meta);
      created = true;
    }
    meta.setAttribute('content', 'noindex, nofollow');

    return () => {
      if (created && meta && meta.parentNode) {
        meta.parentNode.removeChild(meta);
      }
    };
  }, []);

  return (
    <>

      <main id="main-content" className="report-page">
        <Link to="/" className="report-page__back" aria-label="Back to HookCheck home">
          ← Check another message
        </Link>

        {loading && (
          <div className="loading-state" role="status" aria-live="polite">
            <div className="spinner" aria-hidden="true" />
            <p>Loading report…</p>
          </div>
        )}

        {error && (
          <div className="error-state" role="alert">
            <p className="error-state__title">Report unavailable</p>
            <p>{error}</p>
          </div>
        )}

        {report && !loading && (
          <ResultsBlock report={report} />
        )}
      </main>

      <Footer />
    </>
  );
}
